more logging while deploying

diff --git a/.github/workflows/deploy-main-to-aws.yml b/.github/workflows/deploy-main-to-aws.yml
--- a/.github/workflows/deploy-main-to-aws.yml
+++ b/.github/workflows/deploy-main-to-aws.yml
@@ -38,4 +38,4 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
       - name: Deploy
-        run: (cd public && for i in **/*; do if [ -f "$i" ]; then aws s3api put-object --body $i --bucket blog2.claude.nl --key "website/${i%index.html}" --content-type "$(file -b --mime-type "$i")"; fi; done)
+        run: (cd public && for i in **/*; do if [ -f "$i" ]; then echo "$i" && aws s3api put-object --body "$i" --bucket blog2.claude.nl --key "website/${i%index.html}" --content-type "$(file -b --mime-type "$i")" || echo "failed"; fi; done)
